name: studio_partner_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-261.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  rive: ^0.13.2
  http: ^1.2.1
  go_router: ^14.0.2
  shared_preferences: ^2.2.3
  flutter_riverpod: ^2.5.1
  hive_flutter: ^1.1.0
  jwt_decode: ^0.3.1
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.1
  flutter_bloc: ^8.1.5
  smooth_page_indicator: ^1.1.0
  otp_fields: ^0.0.4
  timer_button: ^2.1.1
  alt_sms_autofill: ^1.0.0
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  flutter_custom_drop_down_widget: ^1.0.1
  fpdart: ^1.1.0
  file_picker_writable: ^2.1.0+1
  email_validator_flutter: ^1.0.0
  uuidv6: ^1.0.0+1
  uuid: ^3.0.7
  csc_picker: ^0.2.7
  permission_handler: ^11.3.1
  flutter_map: ^6.1.0
  json_serializable: ^6.8.0
  url_launcher: ^6.2.6
  latlong2: ^0.9.1
  intl: ^0.19.0
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/placeholders/
    - assets/animations/
    - assets/icons/


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
